# Generated by Django 2.1.4 on 2018-12-18 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backers_count', models.IntegerField()),
                ('blurb', models.TextField()),
                ('category', models.TextField()),
                ('converted_pledged_amount', models.IntegerField()),
                ('country', models.TextField()),
                ('created_at', models.TimeField()),
                ('creator', models.TextField()),
                ('currency', models.TextField()),
                ('deadline', models.TimeField()),
                ('disable_communication', models.BooleanField()),
                ('fx_rate', models.FloatField()),
                ('goal', models.IntegerField()),
                ('kick_id', models.IntegerField()),
                ('launched_at', models.TimeField()),
                ('location', models.TextField()),
                ('name', models.TextField()),
                ('photo', models.TextField()),
                ('pledged', models.IntegerField()),
                ('profile', models.TextField()),
                ('slug', models.TextField()),
                ('source_url', models.URLField()),
                ('spotlight', models.BooleanField()),
                ('staff_pick', models.BooleanField()),
                ('state', models.TextField()),
                ('state_changed_at', models.TimeField()),
                ('static_usd_rate', models.FloatField()),
                ('urls', models.TextField()),
                ('usd_pledged', models.FloatField()),
                ('usd_type', models.TextField()),
            ],
        ),
    ]
